### ISSUE TITLE
Open up SentryStackTrace model for development of integrations

### ISSUE THREAD

**Issue by voltcode** [getsentry/sentry-dotnet-protocol#24]
At the moment SentryStackTrace cannot be created outside SentrySdk. This is a pain if one wants to develop custom integrations. 

Would you consider opening it up? We have a case where we want to pass some exception data over several services before it hits Sentry. I can raise a pull request (basically a setter for Frames collection within SentryStackTrace or another way if you want) if you are open to it.

There are way too many internal classes everywhere in my opinion, and it makes it hard to integrate Sentry without resorting to hacks through reflections. I'm not sure if this issue should be raised here or in the main dotnet repo, please redirect me if I'm posting in the wrong place.

**Comment by bruno-garcia** [comment]
@voltcode Sounds fair. It would be great to get a PR on this, thanks!

The types are internal to reduce the public API and therefore what we officially need to maintain/breaking changes. It makes it harder for us to change things and evolve it the SDK otherwise.

Please don't feel like you need to hack with reflection. Just as you did in this issue, raise the need of the API (in this case just making something public) and we can discuss it and get it done. I recall a similar request like this in the old SDK repo (https://github.com/getsentry/raven-csharp/issues/268) too.

**Comment by bruno-garcia** [comment]
@voltcode until these changes are publish to `NuGet`, please consider simply using the `Add` of the current list:

```csharp
var stacktrace = new SentryStackTrace();
foreach (var frame in frames)
{
    stacktrace.Frames.Add(frame);
}

return new SentryException
{
    Stacktrace = stacktrace,
    Type = excType,
    Value = excValue
};
```

Where `frames` is a list of frames you created yourself.
