### ISSUE TITLE
Modify breadcrumb messages

### ISSUE THREAD

**Issue by dlamkins** [getsentry/sentry-dotnet-protocol#46]
Is there a way to modify a breadcrumb's message (or other properties)?  [This doc page](https://docs.sentry.io/error-reporting/configuration/filtering/?platform=csharp#before-breadcrumb) suggests that this is supported on other platforms, but it looks like there are no setters on the `Breadcrumb`s class in .NET, so all properties are read-only.

I think I've seen some folks are getting around this by creating a new breadcrumb in `BeforeBreadcrumb` and returning that instead, but that seems a little heavy handed (and you can't modify the ones stored in `SentryEvent.Breadcrumbs` using this method, either).

Where I would like to use it most is in `BeforeSend`.  We don't send things with Sentry frequently, but we do generate a lot of breadcrumbs under some circumstances and would prefer to do our processing only on the breadcrumbs that are about to be sent instead of on every single one.

**Comment by bruno-garcia** [comment]
`Breadcrumb` is immutable. We could make it mutable but that'd come with some side effects so based on your description it seems like `BeforeBreadcrumb` would work well for you.

We have an example of it here:

https://github.com/getsentry/sentry-dotnet/blob/bc8b6bf9ffe9f34cd1fa9fc0119f2b71b85a6b2e/samples/Sentry.Samples.Console.Customized/Program.cs#L68-L77

This callback is only invoked for events that are about to be sent out. If the dropped due to sampling or some event processor/beforeSend, this callback won't be invoked at all.

**Comment by dlamkins** [comment]
It's good to know that it `BeforeBreadcrumb` is only called on breadcrumbs that are about to be sent.  That significantly reduces the issue then - we thought it meant it would run when the breadcrumb was first noted.

FWIW, the linked code you provided is only for blocking/ignoring a breadcrumb and not for modifying an existing one, so that does not clarify anything in our use case.  Right now we are creating a new breadcrumb instance and returning that, which is working.

Thank you for clarifying!

**Comment by bruno-garcia** [comment]
Glad to know it's working for you. Creating a new instance is the way to go in this case since we have it immutable.
